# Generated by Django 3.2.5 on 2021-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211002_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Emotion',
            field=models.CharField(default='Sadness', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
